import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import  UserProvider  from "@/application/UserProvider";
import { AlertContainer, AlertProvider } from "@/features/alerts";
import { TaskProvider } from "@/entities/task";
import StoreProvider from "@/app/store/storeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <StoreProvider>
          <AlertProvider>
            <AlertContainer />
            <UserProvider>
              <TaskProvider>{children}</TaskProvider>
            </UserProvider>
          </AlertProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
